#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Viktor Varland <varl@vlv.io>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=${PATH}:~/bin
export EDITOR=vim
export TERMINAL=urxvt

eval `dircolors ~/.dircolors`

source ~/.alias

for alias in ~/.alias.*; do
  source "$alias"
done
